#server settings
server:
  port: 8080

spring:
  datasource:
    druid:
      url: "jdbc:mysql://localhost:3306/testOne?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
      username: root
      password: root
      driver-class-name: "com.mysql.jdbc.Driver"
      pool-size: 30
      initialSize: 1
      maxActive: 50
      minIdle: 10
      maxWait: 60000
      validationQuery: select 1 from dual
      validationQueryTimeout: 5
      testWhileIdle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      #statviewConfig 启用Druid内置监控
      stat-view-servlet:
        enabled: true
        reset-enable: true
        login-username: demo
        login-password: demo
      remove-abandoned: true
      remove-abandoned-timeout-millis: 2000000

#myBatis全局配置
mybatis:
  configuration:
    cache-enabled: false
    jdbcTypeForNull: NULL
    default-statement-timeout: 3000
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  type-aliases-package: com.lmh.demo.model

logging:
  config: classpath:log4j2-spring.xml




